const products = [
  {
    id: 0,
    priductImg: "./assest/pic1.jpg",
    productName: "Pound Cake",
    price: 165,
    description: "lemon cake is a moist pound cake",
    isAdded: false,
  },
  {
    id: 1,
    priductImg: "./assest/pic2.jpg",
    productName: "carrot Cake",
    price: 200,
    description: " Sponge cake with almonds",
    isAdded: false,
  },
  {
    id: 2,
    priductImg: "./assest/pic3.jpg",
    productName: "Chiffon Cake",
    price: 145,
    description: "layer of leache flan",
    isAdded: false,
  },
  {
    id: 3,
    priductImg: "./assest/pic4.jpg",
    productName: "Butter Cake",
    price: 30,
    description: "A classic yellow cake",
    isAdded: false,
  },
  {
    id: 4,
    priductImg: "./assest/pic5.jpg",
    productName: "Pineapple Cake",
    price: 180,
    description: "The best birthday cake flovor",
    isAdded: false,
  },
  {
    id: 5,
    priductImg: "./assest/pic6.jpg",
    productName: "Ice creame Cake",
    price: 320,
    description: "layer of water cookies",
    isAdded: false,
  },
  {
    id: 6,
    priductImg: "./assest/pic7.jpg",
    productName: "Coffee Cake",
    price: 195,
    description: "Sweet cake",
    isAdded: false,
  },
  {
    id: 7,
    priductImg: "./assest/pic8.jpg",
    productName: "Fruit Cake",
    price: 100,
    description: "combination of venila and red velvet",
    isAdded: false,
  },
  {
    id: 8,
    priductImg: "./assest/pic9.jpg",
    productName: "Bndt Cake",
    price: 45,
    description: "Baked in Bndt pan",
    isAdded: false,
  },
  {
    id: 9,
    priductImg: "./assest/pic10.jpg",
    productName: "Strawberry Cake",
    price: 150,
    description: "Sweet and luscios",
    isAdded: false,
  },
  {
    id: 10,
    priductImg: "./assest/pic11.jpg",
    productName: "vanila Cake",
    price: 110,
    description: "Visually striking look",
    isAdded: false,
  },
  {
    id: 11,
    priductImg: "./assest/pic12.jpg",
    productName: "marble Cake",
    price: 90,
    description: "Harmonios cake.",
    isAdded: false,
  },
];